apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-checkout-configmap
  namespace: orderly
data:
  PORT: "3002"
  NODE_ENV: "production"
  DB_HOST: "${DB_IP}" # db-service
  DB_USERNAME: "${DB_USERNAME}" # "postgres"
  DB_PORT: "5432"
  DB_PASSWORD: "${DB_PASSWORD}" # "postgres"
  DB_NAME: "${DB_NAME}" # postgres
  DB_DIALECT: postgres

  AMQP_USERNAME: "${BROKER_USER}" # admin
  AMQP_PASSWORD: "${BROKER_PASSWORD}" # admin
  AMQP_COOKIE: "TRIBUFUSTACK"
  AMQP_PORT: "5672"
  AMQP_HOST: broker-service

  CHECKIN_HOST: ms-checkin-service
  CHECKIN_PORT: "3001"
