apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-checkout-deployment
  namespace: orderly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-checkout
  template:
    metadata:
      labels:
        app: ms-checkout
    spec:
      containers:
      - name: ms-checkout-container
        image: dealmachine/checkout-api:2
        workingDir: /usr/checkout/api
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: ms-checkout-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          periodSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3002
          periodSeconds: 5
          failureThreshold: 30
